version: '3'
services:
  node-app:
    build: .
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node-app